### ISSUE TITLE
Setup a docker container to run a "Hello World!" providing instance of the server.

### ISSUE THREAD

**Issue by zancas** [zancas/plearn#2]

**Comment by zancas** [comment]
@grubino thinks it's this to start ye olde' server:

"pserve plearn.ini --reload (I think --reload is to restart when files
changes, not sure)"

**Comment by grubino** [comment]
Here are the dockerhub python images:
https://hub.docker.com/_/python/

Probably want something from the 2.7 group, on debian?

**Comment by zancas** [comment]
Woot, confirm 1 HTTP server microservice:

```bash
0 b: master
/root/plearn/plearn-api :$
wget 127.0.0.1:9999
--2016-04-16 07:11:09--  http://127.0.0.1:9999/
Connecting to 127.0.0.1:9999... connected.
HTTP request sent, awaiting response... 401 Unauthorized

Username/Password Authentication Failed.
```
